-- ============================================================================
--  CRM FORMATION — schéma COMPLET sur la base unifiée (unified-backend)
--  Projet Supabase : lrslisyydbiejqzpsoxc
--  NB : ce schéma a déjà été appliqué + les données migrées depuis
--       backend-formation (29 formations, 8 catégories, 4 organismes, 6 statuts).
--       Ce fichier sert de référence / reproductibilité.
--  Sécurité RLS : lecture/écriture pour accès "crmformation" ou admin ;
--                 suppression réservée à l'admin.
-- ============================================================================

create type if not exists public.crm_lead_stage as enum
  ('nouveau','contacte','qualifie','devis_envoye','gagne','perdu');

create table if not exists public.crm_organismes(
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  nom text not null, actif boolean not null default true
);
create table if not exists public.crm_categories(
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  nom text not null, actif boolean not null default true
);
create table if not exists public.crm_statuts(
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  nom text not null, couleur text, ordre integer not null default 0,
  actif boolean not null default true
);
create table if not exists public.crm_formations(
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  nom text not null,
  tarif numeric default 0, heures_elearning numeric default 0, heures_visio numeric default 0,
  description text, actif boolean not null default true,
  organisme text, prix_min numeric,
  lien_calendly_positionnement text, lien_dof text,
  certification text, type_formation text, categorie text
);
create table if not exists public.crm_leads(
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  prenom text, nom text, email text, telephone text, entreprise text,
  stage public.crm_lead_stage not null default 'nouveau',
  source text, formation text, montant numeric, notes text,
  project_id uuid, owner_id uuid default auth.uid(),
  facture boolean not null default false,
  numero bigint generated by default as identity,
  statut_id uuid references public.crm_statuts(id) on delete set null,
  organisme text,
  etape text not null default 'organisme',   -- parcours : organisme/lien_edof/test_positionnement/entree_formation/facture
  date_test_positionnement date, date_entree_formation date
);
create table if not exists public.crm_lead_formations(
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  lead_id uuid not null references public.crm_leads(id) on delete cascade,
  formation_id uuid references public.crm_formations(id) on delete set null,
  prix numeric
);
create table if not exists public.crm_activities(
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  lead_id uuid not null references public.crm_leads(id) on delete cascade,
  type text not null default 'note', contenu text, owner_id uuid default auth.uid()
);

create or replace function public.has_crm_access()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.app_memberships m
    where m.user_id = auth.uid() and (m.project_key = 'crmformation' or m.role = 'admin'));
$$;
create or replace function public.is_crm_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.app_memberships m
    where m.user_id = auth.uid() and m.role = 'admin');
$$;

do $$
declare t text;
begin
  foreach t in array array['crm_organismes','crm_categories','crm_statuts','crm_formations','crm_leads','crm_lead_formations','crm_activities'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists %I on public.%I', t||'_sel', t);
    execute format('drop policy if exists %I on public.%I', t||'_ins', t);
    execute format('drop policy if exists %I on public.%I', t||'_upd', t);
    execute format('drop policy if exists %I on public.%I', t||'_del', t);
    execute format('create policy %I on public.%I for select using (public.has_crm_access())', t||'_sel', t);
    execute format('create policy %I on public.%I for insert with check (public.has_crm_access())', t||'_ins', t);
    execute format('create policy %I on public.%I for update using (public.has_crm_access()) with check (public.has_crm_access())', t||'_upd', t);
    execute format('create policy %I on public.%I for delete using (public.is_crm_admin())', t||'_del', t);
  end loop;
end $$;
